language: php
sudo: false
php:
- 5.6
- 7.0
- 7.1
- hhvm
- nightly
matrix:
  fast_finish: true
  allow_failures:
  - php: nightly
before_script:
- composer self-update
- composer install --prefer-source --no-interaction --dev
script: phpunit
notifications:
  on_success: never
  on_failure: always
  email: iburn36360@gmail.com
